import {
  GiAchillesHeel,
  GiBarefoot,
  GiBeard,
  GiCircleSparks,
  GiComb,
  GiCutDiamond,
  GiDiamondRing,
  GiElectric,
  GiEngagementRing,
  GiEyelashes,
  GiFemaleLegs,
  GiFingernail,
  GiFingersCrossed,
  GiFlowerStar,
  GiFootprint,
  GiGemPendant,
  GiGems,
  GiGlowingHands,
  GiHairStrands,
  GiHand,
  GiHandOk,
  GiHighHeel,
  GiLeg,
  GiLipstick,
  GiMagicPalm,
  GiMustache,
  GiOpenPalm,
  GiPaintBrush,
  GiPalm,
  GiPencilBrush,
  GiRazor,
  GiRazorBlade,
  GiScissors,
  GiSparkles,
  GiSpray,
  GiStarSwirl,
  GiThumbUp,
  GiTowel,
} from 'react-icons/gi'
import {
  FaBottleDroplet,
  FaDiamond,
  FaGem,
  FaHandSparkles,
  FaSpa,
  FaWandMagicSparkles,
} from 'react-icons/fa6'

export const BARBER_ICONS = [
  { id: 'GiScissors', label: 'Tijeras', Icon: GiScissors },
  { id: 'GiElectric', label: 'Máquina', Icon: GiElectric },
  { id: 'GiRazor', label: 'Navaja', Icon: GiRazor },
  { id: 'GiRazorBlade', label: 'Cuchilla', Icon: GiRazorBlade },
  { id: 'GiBeard', label: 'Barba', Icon: GiBeard },
  { id: 'GiMustache', label: 'Bigote', Icon: GiMustache },
  { id: 'GiComb', label: 'Peine', Icon: GiComb },
  { id: 'GiHairStrands', label: 'Cabello', Icon: GiHairStrands },
  { id: 'GiPaintBrush', label: 'Tinte', Icon: GiPaintBrush },
  { id: 'GiPencilBrush', label: 'Delineado', Icon: GiPencilBrush },
  { id: 'GiTowel', label: 'Toalla', Icon: GiTowel },
  { id: 'GiSpray', label: 'Spray', Icon: GiSpray },

  { id: 'GiFingernail', label: 'Uñas', Icon: GiFingernail },
  { id: 'GiHandOk', label: 'Manicura', Icon: GiHandOk },
  { id: 'GiHand', label: 'Mano', Icon: GiHand },
  { id: 'GiGlowingHands', label: 'Manos', Icon: GiGlowingHands },
  { id: 'GiPalm', label: 'Palma', Icon: GiPalm },
  { id: 'GiOpenPalm', label: 'Palma abierta', Icon: GiOpenPalm },
  { id: 'GiMagicPalm', label: 'Palma mágica', Icon: GiMagicPalm },
  { id: 'GiFingersCrossed', label: 'Dedos', Icon: GiFingersCrossed },
  { id: 'GiThumbUp', label: 'Pulgar', Icon: GiThumbUp },
  { id: 'GiEyelashes', label: 'Pestañas', Icon: GiEyelashes },
  { id: 'GiLipstick', label: 'Labial', Icon: GiLipstick },
  { id: 'GiSparkles', label: 'Brillo', Icon: GiSparkles },
  { id: 'GiCircleSparks', label: 'Destellos', Icon: GiCircleSparks },
  { id: 'GiStarSwirl', label: 'Estrella', Icon: GiStarSwirl },
  { id: 'GiFlowerStar', label: 'Flor', Icon: GiFlowerStar },
  { id: 'GiGems', label: 'Gemas', Icon: GiGems },
  { id: 'GiGemPendant', label: 'Colgante', Icon: GiGemPendant },
  { id: 'GiDiamondRing', label: 'Anillo', Icon: GiDiamondRing },
  { id: 'GiEngagementRing', label: 'Anillo boda', Icon: GiEngagementRing },
  { id: 'GiCutDiamond', label: 'Diamante', Icon: GiCutDiamond },

  { id: 'FaHandSparkles', label: 'Semi', Icon: FaHandSparkles },
  { id: 'FaBottleDroplet', label: 'Esmalte', Icon: FaBottleDroplet },
  { id: 'FaWandMagicSparkles', label: 'Nail art', Icon: FaWandMagicSparkles },
  { id: 'FaSpa', label: 'Spa', Icon: FaSpa },
  { id: 'FaGem', label: 'Gema', Icon: FaGem },
  { id: 'FaDiamond', label: 'Diamante', Icon: FaDiamond },

  { id: 'GiBarefoot', label: 'Pie', Icon: GiBarefoot },
  { id: 'GiFootprint', label: 'Huella', Icon: GiFootprint },
  { id: 'GiAchillesHeel', label: 'Talón', Icon: GiAchillesHeel },
  { id: 'GiHighHeel', label: 'Tacón', Icon: GiHighHeel },
  { id: 'GiLeg', label: 'Pierna', Icon: GiLeg },
  { id: 'GiFemaleLegs', label: 'Piernas', Icon: GiFemaleLegs },
]

export const ICON_BY_ID = BARBER_ICONS.reduce((map, icon) => {
  map[icon.id] = icon
  return map
}, {})
